// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trucks.Repository.Contexts;

#nullable disable

namespace Trucks.Repository.Migrations
{
    [DbContext(typeof(TrucksDBContext))]
    partial class TrucksDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Trucks.Domain.Entities.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("COLOR");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int>("IdTruckModel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_TRUCK_MODEL");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MANUFACTURE_YEAR");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MODEL_YEAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id");

                    b.HasIndex("IdTruckModel");

                    b.ToTable("TB_TRUCK", (string)null);
                });

            modelBuilder.Entity("Trucks.Domain.Entities.TruckModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("TB_TRUCK_MODEL", (string)null);
                });

            modelBuilder.Entity("Trucks.Domain.Entities.Truck", b =>
                {
                    b.HasOne("Trucks.Domain.Entities.TruckModel", "TruckModel")
                        .WithMany("Trucks")
                        .HasForeignKey("IdTruckModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TRUCK_TRUCK_MODEL");

                    b.Navigation("TruckModel");
                });

            modelBuilder.Entity("Trucks.Domain.Entities.TruckModel", b =>
                {
                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
